### ISSUE TITLE
Compatibility with earlier than QT 5.10 broken as of https://github.com/AntiMicroX/antimicrox/commit/61fda62f45ef8713a44f3efe330d0af2f1ec59a4

### ISSUE THREAD

**Issue by theofficialgman** [AntiMicroX/antimicrox#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to build on versions of QT before QT 5.10 as of https://github.com/AntiMicroX/antimicrox/commit/61fda62f45ef8713a44f3efe330d0af2f1ec59a4

startDetached was added in QT 5.10, and unavailable in earlier versions: https://doc.qt.io/qt-5/qprocess.html#startDetached

### Expected Behavior

Able to build on QT 5.9.X and older versions (as was possible before this commit)

### Environment

```markdown
- OS:Ubuntu Bionic 18.04
- AntiMicroX version: master
```

### Anything else?
Error during building:
```
/tmp/antimicrox/src/event.cpp: In function ‘void sendevent(JoyButtonSlot*, bool)’:
/tmp/antimicrox/src/event.cpp:176:50: error: no matching function for call to ‘QProcess::startDetached(qint64*)’
         bool success = process.startDetached(&pid);
                                                  ^
In file included from /usr/include/aarch64-linux-gnu/qt5/QtCore/QProcess:1:0,
                 from /tmp/antimicrox/src/event.cpp:26:
/usr/include/aarch64-linux-gnu/qt5/QtCore/qprocess.h:250:17: note: candidate: static bool QProcess::startDetached(const QString&, const QStringList&, const QString&, qint64*)
     static bool startDetached(const QString &program, const QStringList &arguments,
                 ^~~~~~~~~~~~~
/usr/include/aarch64-linux-gnu/qt5/QtCore/qprocess.h:250:17: note:   candidate expects 4 arguments, 1 provided
/usr/include/aarch64-linux-gnu/qt5/QtCore/qprocess.h:257:17: note: candidate: static bool QProcess::startDetached(const QString&, const QStringList&)
     static bool startDetached(const QString &program, const QStringList &arguments); // ### Qt6: merge overloads
                 ^~~~~~~~~~~~~
/usr/include/aarch64-linux-gnu/qt5/QtCore/qprocess.h:257:17: note:   candidate expects 2 arguments, 1 provided
/usr/include/aarch64-linux-gnu/qt5/QtCore/qprocess.h:259:17: note: candidate: static bool QProcess::startDetached(const QString&)
     static bool startDetached(const QString &command);
                 ^~~~~~~~~~~~~
/usr/include/aarch64-linux-gnu/qt5/QtCore/qprocess.h:259:17: note:   no known conversion for argument 1 from ‘qint64* {aka long long int*}’ to ‘const QString&’

```

I am aware startDetached has existed in the codebase from much earlier, but for whatever reason it was not preventing building until now

**Comment by pktiuk** [comment]
I was aware of this bug (it caused some problems with AppImage build on 18.04), but I hoped nobody will notice until I will fix it ;)
